### ISSUE TITLE
XMLHttpRequest.send() no longer accepts ArrayBuffer as an argument

### ISSUE THREAD

**Issue by glynj-bsquare** [pullstring/pullstring-js#1]
See: https://developer.mozilla.org/en-US/docs/Web/API/XMLHttpRequest/send

When using conversation.sendAudio() a Wav file is passed in as a DataView object.
The data is verified to be 16k mono, and then the audio is extracted as an ArrayBuffer.
This is passed directly to the send() method of XMLHttpRequest, which returns an error.

A simple fix is to convert the audio extracted to a javascript Buffer before returning it.

**Comment by gdamron** [comment]
Thanks for catching this oversight.  I opted for a Uint8Array over Buffer to be more explicit and to be more browser friendly.  Note that if you're using Node, we have a Node-targeted SDK coming very soon.
