### ISSUE TITLE
Allow local callbacks in addition to global onResponse function

### ISSUE THREAD

**Issue by gdamron** [pullstring/pullstring-js#2]
From a recent support request at PullString:

> I've looked into the javascript API, but some features of it won't work
> with my code. I'm mixing Pullstring with socket.io and I can't have a
> global onResponse call. I need to be able to redefine the different
> onResponse with different sockets call.
> 
> 
> If I could do something like this:
> 
> 
> socket.on('new userroom', function(msg){
> 
> 
> socket.join(msg.sessionid);
> conversation.start( MY_PROJECT_ID, request, function( response ){
> 
> // custom on response code
> io.sockets.in(msg.sessionid).emit('bot send', { sessionid : 1, msg
> : output.text, user: 'bot', user: output.character, conversationId:
> response.conversationId } );
> 
> }
> 
> saveClient(msg);
> });

To support technologies like socket.io, we could easily allow both a global ```onResponse``` callback and a locally scoped one. While it seems clear that a local callback would take precedence over a global one, there is a design choice to make about whether the local callback would work in exclusion of the global one.

**Comment by aggrenier** [comment]
Hello, 

I'm just wondering if any progress has been made on this issue, and if we have an ETA for the implementation. 

If there is no ETA, what would you suggest as a workaround? 

Cheers

**Comment by gdamron** [comment]
Thanks for checking in about this. I haven't implemented it yet, but I should get to it in the next week.

**Comment by gdamron** [comment]
sorry for the delay. this was just merged into master, commit 108fed3.

**Comment by gdamron** [comment]
note that use local callbacks, method calls will now look something like:

```
conversation.sendText('my text', null, callback);
```

The callback is always the last parameter of functions that send input to the web api. This means also setting the preceding parameter to null if you are not also passing in a Request object.
